### ISSUE TITLE
visual bug w/ spotify <1.2.13

### ISSUE THREAD

**Issue by fitsfer** [x1yl/BetterSpicetifyAOTYScores#1]
This extension seems to shrink the bottom bar of the client on older versions of spotify with the OG theme. This happens seconds after I launch the app and only goes away when I uninstall AOTY. Also, im pretty sure the old version of this extension didn't do this to older clients. 

![image_2024-08-24_171805858](https://github.com/user-attachments/assets/2de7c9f2-0dd8-43e8-8ef3-4f4563e2b51e)

![image_2024-08-24_171847908](https://github.com/user-attachments/assets/d7a09a1f-ab60-469e-bac9-1552826d0ccd)

**Comment by x1yl** [comment]
I've pushed a fix. Issue was cause by a style change left in from testing.

**Comment by fitsfer** [comment]
Can confirm.
