### ISSUE TITLE
[Feature] Disable Notification

### ISSUE THREAD

**Issue by livejamie** [x1yl/BetterSpicetifyAOTYScores#12]
![image](https://github.com/user-attachments/assets/502943f9-6aa1-40f3-a6ec-7199ae6a094a)

This notification appearing on the mini player is really distracting.

I want to be able to disable it.

Thanks!

**Comment by x1yl** [comment]
Life is getting in the way at the moment but will try to implement soon.

**Comment by x1yl** [comment]
Implemented in b1c5e2b
